workflows:
  ios-app:
    name: iOS App Build
    environment:
      xcode: latest
      vars:
        XCODE_WORKSPACE: "QQ.xcodeproj"   # or QQ.xcworkspace if using CocoaPods
        XCODE_SCHEME: "QQ"                # must match your scheme name in Xcode
    scripts:
      - name: Install dependencies
        script: |
          # Only needed if using CocoaPods
          if [ -f "Podfile" ]; then
            pod install
          fi
      - name: Build for iOS Simulator
        script: |
          xcodebuild clean build \
          -project "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14'
    artifacts:
      - build/ios/**/*.app
